#!/bin/bash
sudo pacman -S --needed obsidian godot love mpv steam lutris winetricks remmina libreoffice-fresh signal-desktop krita blender discord kvantum nwg-look gnome-disk-utility gnome-software goverlay protonmail-bridge-core neovide prismlauncher thunderbird neovide system-config-printer glab github-cli calc bluetui gdu zoxide systemctl-tui engrampa
#proton-vpn-gtk-app


sudo flatpak install flathub app.zen_browser.zen
sudo flatpak install flathub com.heroicgameslauncher.hgl
sudo flatpak install flathub com.usebottles.bottles
sudo flatpak install flathub com.github.Matoking.protontricks
sudo flatpak install flathub com.vysp3r.ProtonPlus
sudo flatpak install flathub dev.vencord.Vesktop
sudo flatpak install flathub com.github.tchx84.Flatseal
sudo flatpak install flathub com.obsproject.Studio
sudo flatpak install flathub org.freedesktop.Platform.VulkanLayer.OBSVkCapture/x86_64/24.08
sudo flatpak install flathub com.obsproject.Studio.Plugin.OBSVkCapture/x86_64/stable
sudo flatpak install flathub org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/24.08
sudo flatpak install flathub org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/24.08
sudo flatpak install flathub org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/24.08
sudo flatpak install flathub org.winehq.Wine.DLLs.dxvk/x86_64/stable-23.08
sudo flatpak install flathub com.github.marhkb.Pods 
sudo flatpak install flathub com.rtosta.zapzap
flatpak override --user com.usebottles.bottles --filesystem=xdg-data/Steam 
flatpak override --user --filesystem=/mnt/raid/SteamLibrary com.github.Matoking.protontricks
