#!/bin/bash
rustup default stable
rustup install stable
#sudo pacman -S --needed rustup base-devel git && git clone https://aur.archlinux.org/paru.git
#cd paru && makepkg -si

paru -S --needed xdg-ninja vkd3d-proton-bin dxvk-bin arrpc cnijfilter2 scangearmp2 opentabletdriver-git vkbasalt vkbasalt-cli lib32-vkbasalt qimgv uwsm limine-snapper-sync wg-client 
systemctl enable --user arrpc opentabletdriver

