#!/bin/bash
paru -S --needed hyprcursor hyprgraphics hypridle hyprland hyprland-protocols hyprland-qtutils hyprlang hyprlock hyprpaper hyprpolkitagent hyprsunset hyprutils hyprwayland-scanner xdg-desktop-portal-hyprland hyprpicker qt5-wayland qt6-wayland kvantum-qt5 uwsm

paru -S --needed ghostty ghostty-shell-integration ghostty-terminfo qt6ct qt5ct kvantum nwg-look waybar 

paru -S --needed pulsemixer cmus calc calcurse brightnessctl batsignal grim slurp neovim lazygit btop lsd bat fish starship pavucontrol wl-clipboard swww zoxide cava libcava clipse pacseek yazi zellij rmpc
#cliphist 
