#!/bin/bash

sudo pacman -S --needed wireguard-tools networkmanager-openvpn networkmanager openvpn openresolv firewalld systemd-resolvconf

echo "wireguard" | sudo tee /etc/modules-load.d/wireguard.conf
systemctl enable --now systemd-resolvconf firewalld
