#!/usr/bin/bash
paru -R networkmanager libnm libnma libnma-common libnma-gtk4 networkmanager-openvpn networkmanager-qt networkmanager-qt5 nm-connection-editor lib32-libnm network-manager-applet
paru -S networkmanager libnm libnma libnma-common libnma-gtk4 networkmanager-openvpn networkmanager-qt networkmanager-qt5 nm-connection-editor lib32-libnm network-manager-applet
